name: ecoville
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  connectivity_plus: ^6.0.1
  dio: ^5.4.1
  equatable: ^2.0.5
  firebase_core: ^2.31.0
  firebase_messaging: ^14.9.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_local_notifications: ^17.1.2
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  get_it: ^7.7.0
  go_router: ^13.2.1
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  hydrated_bloc: ^9.1.4
  image_picker: ^1.0.7
  path: ^1.9.0
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  sqflite: ^2.3.3+1
  supabase_auth_ui: ^0.4.3
  supabase_flutter: ^2.3.4
  toastification: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/authentication/
    - assets/general/
    - assets/icons/
