name: ecoville
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  connectivity_plus: ^6.0.1
  dio: ^5.4.1
  equatable: ^2.0.5
  firebase_core: ^2.31.0
  firebase_messaging: ^14.9.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_local_notifications: ^17.1.2
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  geolocator: ^12.0.0
  get_it: ^7.7.0
  go_router: ^13.2.1
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  hydrated_bloc: ^9.1.4
  image_picker: ^1.0.7
  path: ^1.9.0
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  sqflite: ^2.3.3+1
  supabase_auth_ui: ^0.4.3
  supabase_flutter: ^2.3.4
  toastification: ^1.2.1
  geocoder: 
    path: ./custom_packages/geocoder
  flutter_image_compress: ^2.3.0
  url_launcher: ^6.2.6
  share_plus: ^9.0.0
  path_provider: ^2.1.3
  animated_bottom_navigation_bar: ^1.3.3
  intl: ^0.19.0
  android_intent_plus: ^5.0.2
  flutter_staggered_grid_view: ^0.7.0
  posthog_flutter: ^4.5.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/ecoville.png"
    background_color: "#030533"
    theme_color: "#030533"
  windows:
    generate: true
    image_path: "assets/ecoville.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/ecoville.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/ecoville.png
  color_dark: "#121212"
  image_dark: assets/ecoville.png

  android_12:
    image: assets/ecoville.png
    icon_background_color: "#ffffff"
    image_dark: assets/ecoville.png
    icon_background_color_dark: "#121212"

  web: false


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
