// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD3DMSYIfzxl2wPfPPeEKr3xsaKng_k9Q',
    appId: '1:593038226855:web:4adc1a332d9e0280a3f282',
    messagingSenderId: '593038226855',
    projectId: 'ecoville-eville',
    authDomain: 'ecoville-eville.firebaseapp.com',
    storageBucket: 'ecoville-eville.appspot.com',
    measurementId: 'G-P5DJWWL669',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoWzh8kMrlCb8UUwC4QiByVVU8b25qZD8',
    appId: '1:593038226855:android:30c3efb5dc76b05ba3f282',
    messagingSenderId: '593038226855',
    projectId: 'ecoville-eville',
    storageBucket: 'ecoville-eville.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQK-kl6iycUWbpXGHweVv_oFUWGcMNR7w',
    appId: '1:593038226855:ios:6783337e6be00310a3f282',
    messagingSenderId: '593038226855',
    projectId: 'ecoville-eville',
    storageBucket: 'ecoville-eville.appspot.com',
    iosBundleId: 'com.ecoville.eville',
  );
}
