
name: Android Release and Play Store deploy

on:
  pull_request:
    branches:
      - master

  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      ALIAS: ${{ secrets.ALIAS }}

    strategy:
      matrix:
        node-version: ['20.x']

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "17.x"
      
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: 3.22.2

      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Download Android keystore
        run: |
          echo "${{ secrets.SIGNING_KEY }}" | base64 -d > android/app/key.jks

      - name: Print Current Directory
        run: |
          pwd
        
      - name: Set Keystore File Permissions
        run: |
          chmod 600 android/app/key.jks
        
      - name: Create key.properties
        run: |
          echo "storeFile=key.jks" > android/key.properties
          echo "storePassword=${KEY_STORE_PASSWORD}" >> android/key.properties
          echo "keyPassword=${KEY_PASSWORD}" >> android/key.properties
          echo "keyAlias=${ALIAS}" >> android/key.properties

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Build Android App Bundle
        run: flutter build appbundle
  
      - name: Create service_account.json
        run: echo '${{ secrets.SERVICE_ACCOUNT_JSON }}' > service_account.json

      - name: Create 'whatsnew' Directory
        run: mkdir -p distribution/
      - name: Deploy to Internal Sharing
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: service_account.json
          packageName: com.ecoville.eville
          changesNotSentForReview: true
          releaseFiles: build/app/outputs/bundle/release/app-release.aab
          track: internal
          whatsNewDirectory: distribution/
